### ISSUE TITLE
感觉添加类似于uiautomator2的xpath语法来查找视图节点更合适

### ISSUE THREAD

**Issue by zkywalker** [Krosxx/Android-Auto-Api#36]
kotlin的语法糖虽然说比java代码直接遍历视图节点还是强很多，但是跟uiautomator2的检索语法比还是复杂很多，可以支持一下

**Comment by Krosxx** [comment]
按道理可以直接引入这个库使用

**Comment by zkywalker** [comment]
> 按道理可以直接引入这个库使用

实践了下，感觉Xpath不适合这种节点经常发生变化的场景，还是基于node进行额外的锚点逻辑判断更健壮一些
