### ISSUE TITLE
有没有用java调用这个库的例子啊

### ISSUE THREAD

**Issue by cngege** [Krosxx/Android-Auto-Api#47]
还在学java，想先学习了解一下🎀

**Comment by Krosxx** [comment]
可以 但写起来很不优雅，建议直接studio 新建项目选择 kotlin 语言，学习 kt

**Comment by cngege** [comment]
> 可以 但写起来很不优雅，建议直接studio 新建项目选择 kotlin 语言，学习 kt

在学了，只是项目中很多部分都是用的java代码，不好重构，我先研究着kotlin，是在不行就用java封装个入口吧

**Comment by loveanao** [comment]
我很想抽时间封装一个java版本。。只有根据你的代码弄个java版实现。。。的确接受不来kt的那个优雅。。。和楼上仁兄一样，现有产品都是java的，不能去重构kt ，不能带来实际产品性能提升。。。
